[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.simple"

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
port = 80

[services.web]
port = 80
targetPort = 80
protocol = "HTTP"